name: RELEASE

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: nuvibit/github-workflows/.github/workflows/release.yaml@main
    secrets:
      GH_SA_TOKEN_RO: ${{ secrets.GH_SA_TOKEN_RO }}