name: TERRAFORM FMT & DOCS

on:
  pull_request:
    branches:
      - master

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform Format
        uses: dflook/terraform-fmt@v1
        with:
          path: ./

      - name: Commit files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "noreply@nuvibit.com"
          git diff-index --quiet HEAD || git commit -m "style(terraform fmt): [BOT] terraform fmt [skip ci]" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}

  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update Terraform Docs
        uses: terraform-docs/gh-actions@v0.6.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs(terraform-docs): [BOT] update README [skip ci]"
